// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/customers/customer_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	entities "github.com/fiap-grupo95/os-service-api/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// Mock Customer Repository
type MockCustomerGateway struct {
	mock.Mock
}

func (m *MockCustomerGateway) GetByID(id string) (*entities.Customer, error) {
	args := m.Called(id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*entities.Customer), args.Error(1)
}

func (m *MockCustomerGateway) GetByDocument(CpfCnpj string) (*entities.Customer, error) {
	args := m.Called(CpfCnpj)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*entities.Customer), args.Error(1)
}
