// Code generated by MockGen. DO NOT EDIT.
package mocks

import (
	"github.com/fiap-grupo95/os-service-api/internal/domain/entities"
	"github.com/fiap-grupo95/os-service-api/internal/domain/valueobject"

	"github.com/stretchr/testify/mock"
)

type MockIVehicleGateway struct {
	mock.Mock
}

func NewMockIVehicleGateway() *MockIVehicleGateway {
	return &MockIVehicleGateway{}
}

func (m *MockIVehicleGateway) FindAll() ([]entities.Vehicle, error) {
	args := m.Called()
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]entities.Vehicle), args.Error(1)
}

func (m *MockIVehicleGateway) FindByID(id uint) (*entities.Vehicle, error) {
	args := m.Called(id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*entities.Vehicle), args.Error(1)
}

func (m *MockIVehicleGateway) FindByPlate(plate valueobject.Plate) (*entities.Vehicle, error) {
	args := m.Called(plate)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*entities.Vehicle), args.Error(1)
}

func (m *MockIVehicleGateway) FindByCustomerID(customerID uint) ([]entities.Vehicle, error) {
	args := m.Called(customerID)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]entities.Vehicle), args.Error(1)
}

func (m *MockIVehicleGateway) Create(vehicle entities.Vehicle) (*entities.Vehicle, error) {
	args := m.Called(vehicle)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*entities.Vehicle), args.Error(1)
}

func (m *MockIVehicleGateway) Update(vehicle entities.Vehicle) error {
	args := m.Called(vehicle)
	return args.Error(0)
}

func (m *MockIVehicleGateway) Delete(id uint) error {
	args := m.Called(id)
	return args.Error(0)
}
