// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/parts_supply/parts_supply_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	entities "github.com/fiap-grupo95/os-service-api/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// Mock Parts Supply Gateway
type MockPartsSupplyGateway struct {
	mock.Mock
}

func (m *MockPartsSupplyGateway) GetByID(ctx context.Context, id string) (*entities.PartsSupply, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*entities.PartsSupply), args.Error(1)
}

func (m *MockPartsSupplyGateway) GetByServiceOrderID(ctx context.Context, serviceOrderID string) ([]entities.PartsSupply, error) {
	args := m.Called(ctx, serviceOrderID)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]entities.PartsSupply), args.Error(1)
}

func (m *MockPartsSupplyGateway) Reserve(ctx context.Context, partsSupply []entities.PartsSupply) error {
	args := m.Called(ctx, partsSupply)
	return args.Error(0)
}

func (m *MockPartsSupplyGateway) Release(ctx context.Context, partsSupply []entities.PartsSupply) error {
	args := m.Called(ctx, partsSupply)
	return args.Error(0)
}

func (m *MockPartsSupplyGateway) WriteOff(ctx context.Context, partsSupply []entities.PartsSupply) error {
	args := m.Called(ctx, partsSupply)
	return args.Error(0)
}

func (m *MockPartsSupplyGateway) AuthorizeReserve(ctx context.Context, partsSupply []entities.PartsSupply) error {
	args := m.Called(ctx, partsSupply)
	return args.Error(0)
}

func (m *MockPartsSupplyGateway) Update(ctx context.Context, partsSupply *entities.PartsSupply) error {
	args := m.Called(ctx, partsSupply)
	return args.Error(0)
}
