// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/parts_supply/parts_supply_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	entities "mecanica_xpto/internal/domain/entities"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIPartsSupplyRepo is a mock of IPartsSupplyRepo interface.
type MockIPartsSupplyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIPartsSupplyRepoMockRecorder
}

// MockIPartsSupplyRepoMockRecorder is the mock recorder for MockIPartsSupplyRepo.
type MockIPartsSupplyRepoMockRecorder struct {
	mock *MockIPartsSupplyRepo
}

// NewMockIPartsSupplyRepo creates a new mock instance.
func NewMockIPartsSupplyRepo(ctrl *gomock.Controller) *MockIPartsSupplyRepo {
	mock := &MockIPartsSupplyRepo{ctrl: ctrl}
	mock.recorder = &MockIPartsSupplyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPartsSupplyRepo) EXPECT() *MockIPartsSupplyRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIPartsSupplyRepo) Create(ctx context.Context, ps *entities.PartsSupply) (entities.PartsSupply, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, ps)
	ret0, _ := ret[0].(entities.PartsSupply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIPartsSupplyRepoMockRecorder) Create(ctx, ps interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIPartsSupplyRepo)(nil).Create), ctx, ps)
}

// Delete mocks base method.
func (m *MockIPartsSupplyRepo) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIPartsSupplyRepoMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIPartsSupplyRepo)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockIPartsSupplyRepo) GetByID(ctx context.Context, id uint) (entities.PartsSupply, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entities.PartsSupply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIPartsSupplyRepoMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIPartsSupplyRepo)(nil).GetByID), ctx, id)
}

// GetByName mocks base method.
func (m *MockIPartsSupplyRepo) GetByName(ctx context.Context, name string) (entities.PartsSupply, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(entities.PartsSupply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockIPartsSupplyRepoMockRecorder) GetByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockIPartsSupplyRepo)(nil).GetByName), ctx, name)
}

// GetByServiceOrderID mocks base method.
func (m *MockIPartsSupplyRepo) GetByServiceOrderID(ctx context.Context, serviceOrderID uint) ([]entities.PartsSupply, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByServiceOrderID", ctx, serviceOrderID)
	ret0, _ := ret[0].([]entities.PartsSupply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByServiceOrderID indicates an expected call of GetByServiceOrderID.
func (mr *MockIPartsSupplyRepoMockRecorder) GetByServiceOrderID(ctx, serviceOrderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByServiceOrderID", reflect.TypeOf((*MockIPartsSupplyRepo)(nil).GetByServiceOrderID), ctx, serviceOrderID)
}

// List mocks base method.
func (m *MockIPartsSupplyRepo) List(ctx context.Context) ([]entities.PartsSupply, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entities.PartsSupply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIPartsSupplyRepoMockRecorder) List(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIPartsSupplyRepo)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockIPartsSupplyRepo) Update(ctx context.Context, ps *entities.PartsSupply) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, ps)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIPartsSupplyRepoMockRecorder) Update(ctx, ps interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIPartsSupplyRepo)(nil).Update), ctx, ps)
}
