// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/service_order/service_order_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	"context"

	entities "github.com/fiap-grupo95/os-service-api/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// Mock Service Order Repository
type MockServiceOrderGateway struct {
	mock.Mock
}

func NewMockServiceOrderGateway() *MockServiceOrderGateway {
	return &MockServiceOrderGateway{}
}

func (m *MockServiceOrderGateway) Create(ctx context.Context, serviceOrder *entities.ServiceOrder) (*entities.ServiceOrder, error) {
	args := m.Called(ctx, serviceOrder)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*entities.ServiceOrder), nil
}

func (m *MockServiceOrderGateway) GetByID(ctx context.Context, id string, isFullData bool) (*entities.ServiceOrder, error) {
	args := m.Called(ctx, id, isFullData)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	switch value := args.Get(0).(type) {
	case *entities.ServiceOrder:
		return value, args.Error(1)
	case entities.ServiceOrder:
		return &value, args.Error(1)
	default:
		return nil, args.Error(1)
	}
}

func (m *MockServiceOrderGateway) Update(ctx context.Context, serviceOrder *entities.ServiceOrder) error {
	args := m.Called(serviceOrder)
	return args.Error(0)
}

func (m *MockServiceOrderGateway) List(ctx context.Context) ([]*entities.ServiceOrder, error) {
	args := m.Called()
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}

	switch value := args.Get(0).(type) {
	case []*entities.ServiceOrder:
		return value, args.Error(1)
	case []entities.ServiceOrder:
		result := make([]*entities.ServiceOrder, 0, len(value))
		for _, item := range value {
			itemCopy := item
			result = append(result, &itemCopy)
		}
		return result, args.Error(1)
	default:
		return nil, args.Error(1)
	}
}
