// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/service_order/service_order_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	"context"
	entities "github.com/fiap-grupo95/os-service-api/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
	dto "github.com/fiap-grupo95/os-service-api/internal/infrastructure/database/model"
)

// Mock Service Order Repository
type MockServiceOrderGateway struct {
	mock.Mock
}

func NewMockServiceOrderGateway() *MockServiceOrderGateway {
	return &MockServiceOrderGateway{}
}

func (m *MockServiceOrderGateway) UpdateEstimate(ctx context.Context, id uint, estimate float64) error {
	args := m.Called(id, estimate)
	return args.Error(0)
}

func (m *MockServiceOrderGateway) GetByName(ctx context.Context, name string) (entities.Service, error) {
	args := m.Called(ctx, name)
	if args.Get(0) == nil {
		return entities.Service{}, args.Error(1)
	}
	return args.Get(0).(entities.Service), args.Error(1)
}
func (m *MockServiceOrderGateway) Delete(ctx context.Context, id uint) error {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return args.Error(1)
	}
	return args.Error(0)
}

func (m *MockServiceOrderGateway) Create(ctx context.Context, serviceOrder *entities.ServiceOrder) (*entities.ServiceOrder, error) {
	args := m.Called(serviceOrder)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*entities.ServiceOrder), nil
}

func (m *MockServiceOrderGateway) GetByID(ctx context.Context, id uint, isFullData bool) (*entities.ServiceOrder, error) {
	args := m.Called(id, isFullData)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	switch value := args.Get(0).(type) {
	case *entities.ServiceOrder:
		return value, args.Error(1)
	case entities.ServiceOrder:
		return &value, args.Error(1)
	case *dto.ServiceOrderModel:
		return value.ToDomain(), args.Error(1)
	case dto.ServiceOrderModel:
		copy := value
		return copy.ToDomain(), args.Error(1)
	default:
		return nil, args.Error(1)
	}
}

func (m *MockServiceOrderGateway) Update(ctx context.Context, serviceOrder *entities.ServiceOrder) error {
	args := m.Called(serviceOrder)
	return args.Error(0)
}

func (m *MockServiceOrderGateway) List(ctx context.Context) ([]*entities.ServiceOrder, error) {
	args := m.Called()
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}

	switch value := args.Get(0).(type) {
	case []*entities.ServiceOrder:
		return value, args.Error(1)
	case []entities.ServiceOrder:
		result := make([]*entities.ServiceOrder, 0, len(value))
		for _, item := range value {
			itemCopy := item
			result = append(result, &itemCopy)
		}
		return result, args.Error(1)
	case []dto.ServiceOrderModel:
		result := make([]*entities.ServiceOrder, 0, len(value))
		for _, item := range value {
			itemCopy := item
			result = append(result, itemCopy.ToDomain())
		}
		return result, args.Error(1)
	default:
		return nil, args.Error(1)
	}
}

func (m *MockServiceOrderGateway) GetPartsSupplyServiceOrder(ctx context.Context, partsSupplyID uint, serviceOrderID uint) (*entities.ServiceOrderPartsSupply, error) {
	args := m.Called(partsSupplyID, serviceOrderID)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	switch value := args.Get(0).(type) {
	case *entities.ServiceOrderPartsSupply:
		return value, args.Error(1)
	case entities.ServiceOrderPartsSupply:
		return &value, args.Error(1)
	case *dto.PartsSupplyServiceOrder:
		return &entities.ServiceOrderPartsSupply{
			PartsSupplyID:  value.PartsSupplyID,
			ServiceOrderID: value.ServiceOrderID,
			Quantity:       value.Quantity,
		}, args.Error(1)
	case dto.PartsSupplyServiceOrder:
		return &entities.ServiceOrderPartsSupply{
			PartsSupplyID:  value.PartsSupplyID,
			ServiceOrderID: value.ServiceOrderID,
			Quantity:       value.Quantity,
		}, args.Error(1)
	default:
		return nil, args.Error(1)
	}
}
