// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/service/service_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	entities "github.com/fiap-grupo95/os-service-api/internal/domain/entities"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIServiceRepo is a mock of IServiceRepo interface.
type MockIServiceGateway struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceGatewayMockRecorder
}

// MockIServiceGatewayMockRecorder is the mock recorder for MockIServiceGateway.
type MockIServiceGatewayMockRecorder struct {
	mock *MockIServiceGateway
}

// NewMockIServiceGateway creates a new mock instance.
func NewMockIServiceGateway(ctrl *gomock.Controller) *MockIServiceGateway {
	mock := &MockIServiceGateway{ctrl: ctrl}
	mock.recorder = &MockIServiceGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIServiceGateway) EXPECT() *MockIServiceGatewayMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIServiceGateway) Create(ctx context.Context, so *entities.Service) (entities.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, so)
	ret0, _ := ret[0].(entities.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIServiceGatewayMockRecorder) Create(ctx, so interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIServiceGateway)(nil).Create), ctx, so)
}

// Delete mocks base method.
func (m *MockIServiceGateway) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIServiceGatewayMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIServiceGateway)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockIServiceGateway) GetByID(ctx context.Context, id uint) (entities.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entities.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIServiceGatewayMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIServiceGateway)(nil).GetByID), ctx, id)
}

// GetByName mocks base method.
func (m *MockIServiceGateway) GetByName(ctx context.Context, name string) (entities.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(entities.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockIServiceGatewayMockRecorder) GetByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockIServiceGateway)(nil).GetByName), ctx, name)
}

// List mocks base method.
func (m *MockIServiceGateway) List(ctx context.Context) ([]entities.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entities.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIServiceGatewayMockRecorder) List(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIServiceGateway)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockIServiceGateway) Update(ctx context.Context, so *entities.Service) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, so)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIServiceGatewayMockRecorder) Update(ctx, so interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIServiceGateway)(nil).Update), ctx, so)
}
