// Code generated by MockGen. DO NOT EDIT.
package mocks

import (
	"github.com/fiap-grupo95/os-service-api/internal/domain/entities"

	"github.com/stretchr/testify/mock"
)

// Mock Vehicle Repository - "github.com/stretchr/testify/mock"
type MockVehicleGateway struct {
	mock.Mock
}

func (m *MockVehicleGateway) FindByID(id string) (*entities.Vehicle, error) {
	args := m.Called(id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}

	switch v := args.Get(0).(type) {
	case *entities.Vehicle:
		return v, args.Error(1)
	case entities.Vehicle:
		return &v, args.Error(1)
	default:
		return nil, args.Error(1)
	}
}