DROP INDEX IF EXISTS idx_vehicle_customer_id;
DROP INDEX IF EXISTS idx_customer_document;
DROP TABLE IF EXISTS vehicle CASCADE;
DROP TABLE IF EXISTS customer CASCADE;
DROP TABLE IF EXISTS service CASCADE;