apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: os-service-api
data:
    JWT_SECRET: Y2hhdmVfbXVpdG9fc2VndXJh
    NEW_RELIC_LICENSE_KEY: YTY0MmMzZGQ5NjRkZWY5MTMwNzM2MTBlYWMyYzc4ODlGRkZGTlJBTA==
    MONGODB_URI: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvb3Mtc2VydmljZS1kYg==
    MONGODB_USERNAME: dXNlcg==
    MONGODB_PASSWORD: cGFzc3dvcmQ=