apiVersion: v1
kind: Service
metadata:
  name: os-service-api-service
  namespace: os-service-api
spec:
  selector:
    app: os-service-api
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer