// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/interfaces/customer_repository_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	entities "github.com/fiap-grupo95/os-service-api/internal/domain/entities"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockICustomerGateway is a mock of ICustomerGateway interface.
type MockICustomerGateway struct {
	ctrl     *gomock.Controller
	recorder *MockICustomerGatewayMockRecorder
}

// MockICustomerGatewayMockRecorder is the mock recorder for MockICustomerGateway.
type MockICustomerGatewayMockRecorder struct {
	mock *MockICustomerGateway
}

// NewMockICustomerGateway creates a new mock instance.
func NewMockICustomerGateway(ctrl *gomock.Controller) *MockICustomerGateway {
	mock := &MockICustomerGateway{ctrl: ctrl}
	mock.recorder = &MockICustomerGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICustomerGateway) EXPECT() *MockICustomerGatewayMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockICustomerGateway) Create(customer *entities.Customer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", customer)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockICustomerGatewayMockRecorder) Create(customer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockICustomerGateway)(nil).Create), customer)
}

// Delete mocks base method.
func (m *MockICustomerGateway) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockICustomerGatewayMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockICustomerGateway)(nil).Delete), id)
}

// GetByDocument mocks base method.
func (m *MockICustomerGateway) GetByDocument(CpfCnpj string) (*entities.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDocument", CpfCnpj)
	ret0, _ := ret[0].(*entities.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDocument indicates an expected call of GetByDocument.
func (mr *MockICustomerGatewayMockRecorder) GetByDocument(CpfCnpj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDocument", reflect.TypeOf((*MockICustomerGateway)(nil).GetByDocument), CpfCnpj)
}

// GetByID mocks base method.
func (m *MockICustomerGateway) GetByID(id uint) (*entities.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*entities.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockICustomerGatewayMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockICustomerGateway)(nil).GetByID), id)
}

// List mocks base method.
func (m *MockICustomerGateway) List() ([]entities.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]entities.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockICustomerGatewayMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockICustomerGateway)(nil).List))
}

// Update mocks base method.
func (m *MockICustomerGateway) Update(customer *entities.Customer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", customer)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockICustomerGatewayMockRecorder) Update(customer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockICustomerGateway)(nil).Update), customer)
}
