// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/use_cases/customer/customer_use_cases.go

// Package mocks is a generated GoMock package.
package mocks

import (
	"github.com/fiap-grupo95/os-service-api/internal/domain/entities"
	"github.com/stretchr/testify/mock"
)

// MockICustomerUseCase is a mock of ICustomerUseCase interface.
type MockICustomerUseCase struct {
	mock.Mock
}

// NewMockICustomerUseCase creates a new mock instance.
func NewMockICustomerUseCase(_ interface{}) *MockICustomerUseCase {
	return &MockICustomerUseCase{}
}

// CreateCustomer mocks base method.
func (m *MockICustomerUseCase) CreateCustomer(customer *entities.Customer) (*entities.Customer, error) {
	args := m.Called(customer)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*entities.Customer), args.Error(1)
}

// DeleteCustomer mocks base method.
func (m *MockICustomerUseCase) DeleteCustomer(id uint) error {
	args := m.Called(id)
	return args.Error(0)
}

// GetByDocument mocks base method.
func (m *MockICustomerUseCase) GetByDocument(CpfCnpj string) (*entities.Customer, error) {
	args := m.Called(CpfCnpj)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*entities.Customer), args.Error(1)
}

// GetById mocks base method.
func (m *MockICustomerUseCase) GetById(id uint) (*entities.Customer, error) {
	args := m.Called(id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*entities.Customer), args.Error(1)
}

// ListCustomer mocks base method.
func (m *MockICustomerUseCase) ListCustomer() ([]entities.Customer, error) {
	args := m.Called()
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]entities.Customer), args.Error(1)
}

// UpdateCustomer mocks base method.
func (m *MockICustomerUseCase) UpdateCustomer(id uint, customer *entities.Customer) error {
	args := m.Called(id, customer)
	return args.Error(0)
}
