// Code generated by MockGen. DO NOT EDIT.
// Source: parts_supply_use_case.go
//
// Generated by this command:
//
//	mockgen -source=parts_supply_use_case.go -destination=../mocks/parts_supply_use_case_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	"context"

	"github.com/fiap-grupo95/os-service-api/internal/domain/entities"
	"github.com/stretchr/testify/mock"
)

// MockIPartsSupplyUseCase is a mock of IPartsSupplyUseCase interface.
type MockIPartsSupplyUseCase struct {
	mock.Mock
}

// NewMockIPartsSupplyUseCase creates a new mock instance.
func NewMockIPartsSupplyUseCase(_ interface{}) *MockIPartsSupplyUseCase {
	return &MockIPartsSupplyUseCase{}
}

func (m *MockIPartsSupplyUseCase) GetPartsSupplyByServiceOrderID(ctx context.Context, serviceOrderID uint) ([]entities.PartsSupply, error) {
	args := m.Called(ctx, serviceOrderID)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]entities.PartsSupply), args.Error(1)
}

// CreatePartsSupply mocks base method.
func (m *MockIPartsSupplyUseCase) CreatePartsSupply(ctx context.Context, partsSupply *entities.PartsSupply) (entities.PartsSupply, error) {
	args := m.Called(ctx, partsSupply)
	if args.Get(0) == nil {
		return entities.PartsSupply{}, args.Error(1)
	}
	return args.Get(0).(entities.PartsSupply), args.Error(1)
}

// DeletePartsSupply mocks base method.
func (m *MockIPartsSupplyUseCase) DeletePartsSupply(ctx context.Context, id uint) error {
	args := m.Called(ctx, id)
	return args.Error(0)
}

// GetPartsSupplyByID mocks base method.
func (m *MockIPartsSupplyUseCase) GetPartsSupplyByID(ctx context.Context, id uint) (entities.PartsSupply, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return entities.PartsSupply{}, args.Error(1)
	}
	return args.Get(0).(entities.PartsSupply), args.Error(1)
}

// ListPartsSupplies mocks base method.
func (m *MockIPartsSupplyUseCase) ListPartsSupplies(ctx context.Context) ([]entities.PartsSupply, error) {
	args := m.Called(ctx)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]entities.PartsSupply), args.Error(1)
}

// UpdatePartsSupply mocks base method.
func (m *MockIPartsSupplyUseCase) UpdatePartsSupply(ctx context.Context, partsSupply *entities.PartsSupply) error {
	args := m.Called(ctx, partsSupply)
	return args.Error(0)
}
