// Code generated by MockGen. DO NOT EDIT.
// Source: payment_usecase.go
//
// Generated by this command:
//
//	mockgen -source=payment_usecase.go -destination=../mocks/payment_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	"context"

	"github.com/fiap-grupo95/os-service-api/internal/domain/entities"
	"github.com/stretchr/testify/mock"
)

// MockIPaymentUseCase is a mock of IPaymentUseCase interface.
type MockIPaymentUseCase struct {
	mock.Mock
}

// NewMockIPaymentUseCase creates a new mock instance.
func NewMockIPaymentUseCase(_ interface{}) *MockIPaymentUseCase {
	return &MockIPaymentUseCase{}
}

// CreatePayment mocks base method.
func (m *MockIPaymentUseCase) CreatePayment(ctx context.Context, payment *entities.Payment) (*entities.Payment, error) {
	args := m.Called(ctx, payment)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*entities.Payment), args.Error(1)
}

// GetPaymentByID mocks base method.
func (m *MockIPaymentUseCase) GetPaymentByID(ctx context.Context, id uint) (*entities.Payment, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*entities.Payment), args.Error(1)
}

// ListPayments mocks base method.
func (m *MockIPaymentUseCase) ListPayments(ctx context.Context) ([]entities.Payment, error) {
	args := m.Called(ctx)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]entities.Payment), args.Error(1)
}
