// Code generated by MockGen. DO NOT EDIT.
// Source: service_order_usecase.go
//
// Generated by this command:
//
//	mockgen -source=service_order_usecase.go -destination=../mocks/service_order_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	"context"

	"github.com/fiap-grupo95/os-service-api/internal/domain/entities"
	"github.com/stretchr/testify/mock"
)

// MockIServiceOrderUseCase is a mock of IServiceOrderUseCase interface.
type MockIServiceOrderUseCase struct {
	mock.Mock
}

// NewMockIServiceOrderUseCase creates a new mock instance.
func NewMockIServiceOrderUseCase(_ interface{}) *MockIServiceOrderUseCase {
	return &MockIServiceOrderUseCase{}
}

// CreateServiceOrder mocks base method.
func (m *MockIServiceOrderUseCase) CreateServiceOrder(ctx context.Context, serviceOrder entities.ServiceOrder) (*entities.ServiceOrder, error) {
	args := m.Called(ctx, serviceOrder)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*entities.ServiceOrder), args.Error(1)
}

// GetServiceOrder mocks base method.
func (m *MockIServiceOrderUseCase) GetServiceOrder(ctx context.Context, serviceOrder entities.ServiceOrder) (*entities.ServiceOrder, error) {
	args := m.Called(ctx, serviceOrder)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*entities.ServiceOrder), args.Error(1)
}

// ListServiceOrders mocks base method.
func (m *MockIServiceOrderUseCase) ListServiceOrders(ctx context.Context) ([]*entities.ServiceOrder, error) {
	args := m.Called(ctx)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]*entities.ServiceOrder), args.Error(1)
}

// UpdateServiceOrder mocks base method.
func (m *MockIServiceOrderUseCase) UpdateServiceOrder(ctx context.Context, serviceOrder entities.ServiceOrder, flow string) (*entities.ServiceOrder, error) {
	args := m.Called(ctx, serviceOrder, flow)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*entities.ServiceOrder), args.Error(1)
}
