// Code generated by MockGen. DO NOT EDIT.
// Source: service_use_case.go
//
// Generated by this command:
//
//	mockgen -source=service_use_case.go -destination=../mocks/service_use_case_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	"context"

	"github.com/fiap-grupo95/os-service-api/internal/domain/entities"
	"github.com/stretchr/testify/mock"
)

// MockIServiceUseCase is a mock of IServiceUseCase interface.
type MockIServiceUseCase struct {
	mock.Mock
}

// NewMockIServiceUseCase creates a new mock instance.

func NewMockIServiceUseCase() *MockIServiceUseCase {
	return &MockIServiceUseCase{}
}

// CreateService mocks base method.
func (m *MockIServiceUseCase) CreateService(ctx context.Context, service *entities.Service) (entities.Service, error) {
	args := m.Called(ctx, service)
	if args.Get(0) == nil {
		return entities.Service{}, args.Error(1)
	}
	return args.Get(0).(entities.Service), args.Error(1)
}

// DeleteService mocks base method.
func (m *MockIServiceUseCase) DeleteService(ctx context.Context, id uint) error {
	args := m.Called(ctx, id)
	return args.Error(0)
}

// GetServiceByID mocks base method.
func (m *MockIServiceUseCase) GetServiceByID(ctx context.Context, id uint) (entities.Service, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return entities.Service{}, args.Error(1)
	}
	return args.Get(0).(entities.Service), args.Error(1)
}

// ListServices mocks base method.
func (m *MockIServiceUseCase) ListServices(ctx context.Context) ([]entities.Service, error) {
	args := m.Called(ctx)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]entities.Service), args.Error(1)
}

// UpdateService mocks base method.
func (m *MockIServiceUseCase) UpdateService(ctx context.Context, service *entities.Service) error {
	args := m.Called(ctx, service)
	return args.Error(0)
}
