name: Publish Release Image to Docker Hub

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get latest version
        id: get_version
        run: |
          # Fetch all tags, filter for semantic versions, and sort to get the latest
          LATEST_VERSION=$(curl -s "https://hub.docker.com/v2/repositories/mandaapag03/os-service-api/tags/?page_size=100" \
            | jq -r '.results[].name' \
            | grep -oP '^v\d+\.\d+\.\d+' \
            | sort -V \
            | tail -n 1)
          if [ -z "$LATEST_VERSION" ]; then
            LATEST_VERSION="v0.0.0"
          fi
          
          # Extract version numbers
          MAJOR=$(echo $LATEST_VERSION | cut -d. -f1 | tr -d 'v')
          MINOR=$(echo $LATEST_VERSION | cut -d. -f2)
          PATCH=$(echo $LATEST_VERSION | cut -d. -f3)
          
          # Increment patch version
          NEW_MINOR=$((MINOR + 1))
          NEW_VERSION="v$MAJOR.$NEW_MINOR.0"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "New version will be: $NEW_VERSION"

      - name: Build and tag Docker image
        run: |
          docker build . --file Dockerfile --tag mandaapag03/os-service-api:${{ env.NEW_VERSION }}-rc

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push mandaapag03/os-service-api:${{ env.NEW_VERSION }}-rc